[package]
name = "pipelines"
version = "0.1.0"
authors = ["David King <dking@ketralnis.com>"]

[dependencies]

[dev-dependencies]
env_logger = "0.4.3"
flate2 = "0.2.19"
humansize = "1.0.1"
log = "0.3.8"
num_cpus = "1.0"
walkdir = "1.0.7"
